#!/usr/bin/env python3
#Read the content of Dracula and print each line out

foo= open("dracula.txt","r")

# Print the lines that have Vampire to a text file

counter= 0

with open("dracula.txt","r") as foo:
    with open("vampytimex.txt","w") as fang:
        for line in foo:
            if "vampire" in line.lower():
                print(line)
                counter += 1
                fang.write(line)

print(counter)

